apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hearo-admin-tls
spec:
  secretName: hearo-admin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - admin.hearo-hearo.com

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hearo-admin-api-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /api

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hearo-admin-api-redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hearo-admin-api-http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`admin.hearo-hearo.com`) && (Path(`/api`) || PathPrefix(`/api/`))
      priority: 200
      middlewares:
        - name: hearo-admin-api-redirect-https
      services:
        - name: hearo-admin-backend
          port: 8083

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hearo-admin-api
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`admin.hearo-hearo.com`) && (Path(`/api`) || PathPrefix(`/api/`))
      priority: 200
      middlewares:
        - name: hearo-admin-api-strip-prefix
      services:
        - name: hearo-admin-backend
          port: 8083
  tls:
    secretName: hearo-admin-tls
